name: Model Inference

on: [push]

jobs:
  inference:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
    
    - name: Run inference
      run: |
        python -c "
        from sentiment_classifier import SentimentClassifier
        classifier = SentimentClassifier()
        test_texts = [
            # Clear positive/negative examples
            'This is a fantastic day!',
            'The service was terrible.',
            
            # Mixed or complex emotions
            'The movie was interesting but also quite disturbing.',
            'I am feeling nostalgic about the past, both happy and sad memories.',
            'It could have been worse, but it could have been better too.',
            'The experience was bittersweet.',
            'I am not sure how to feel about this situation.',
            'The ending was unexpected, leaving me with mixed feelings.',
            
            # Subtle or neutral statements
            'This is different from what I expected.',
            'The weather is changing.'
        ]
        print('\nRunning sentiment analysis on test sentences:')
        for text in test_texts:
            result = classifier.predict(text)
            print(f'\nText: {text}')
            print(f'Sentiment: {result[\"label\"]}')
            print(f'Confidence: {result[\"score\"]:.4f}')" 