name: Model Inference

on: [push]

jobs:
  inference:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
    
    - name: Run inference
      run: |
        python -c "
        from sentiment_classifier import SentimentClassifier
        classifier = SentimentClassifier()
        test_texts = [
            'This is a fantastic day!',
            'I am feeling very disappointed.',
            'The product quality is excellent.',
            'The service was terrible.'
        ]
        print('\nRunning sentiment analysis on test sentences:')
        for text in test_texts:
            result = classifier.predict(text)
            print(f'\nText: {text}')
            print(f'Sentiment: {result[\"label\"]}')
            print(f'Confidence: {result[\"score\"]:.4f}')" 